from setuptools import setup

setup(
    name='similar-image-detection',
    version='1.0',
    packages=['venv.lib.python3.6.site-packages.PIL', 'venv.lib.python3.6.site-packages.pip',
              'venv.lib.python3.6.site-packages.pip._vendor', 'venv.lib.python3.6.site-packages.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.6.site-packages.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip._internal', 'venv.lib.python3.6.site-packages.pip._internal.req',
              'venv.lib.python3.6.site-packages.pip._internal.vcs',
              'venv.lib.python3.6.site-packages.pip._internal.utils',
              'venv.lib.python3.6.site-packages.pip._internal.models',
              'venv.lib.python3.6.site-packages.pip._internal.commands',
              'venv.lib.python3.6.site-packages.pip._internal.operations', 'venv.lib.python3.6.site-packages.idna',
              'venv.lib.python3.6.site-packages.pywt', 'venv.lib.python3.6.site-packages.pywt.data',
              'venv.lib.python3.6.site-packages.pywt._extensions', 'venv.lib.python3.6.site-packages.numpy',
              'venv.lib.python3.6.site-packages.numpy.ma', 'venv.lib.python3.6.site-packages.numpy.ma.tests',
              'venv.lib.python3.6.site-packages.numpy.doc', 'venv.lib.python3.6.site-packages.numpy.fft',
              'venv.lib.python3.6.site-packages.numpy.fft.tests', 'venv.lib.python3.6.site-packages.numpy.lib',
              'venv.lib.python3.6.site-packages.numpy.lib.tests', 'venv.lib.python3.6.site-packages.numpy.core',
              'venv.lib.python3.6.site-packages.numpy.core.tests', 'venv.lib.python3.6.site-packages.numpy.f2py',
              'venv.lib.python3.6.site-packages.numpy.f2py.tests', 'venv.lib.python3.6.site-packages.numpy.tests',
              'venv.lib.python3.6.site-packages.numpy.compat', 'venv.lib.python3.6.site-packages.numpy.compat.tests',
              'venv.lib.python3.6.site-packages.numpy.linalg', 'venv.lib.python3.6.site-packages.numpy.linalg.tests',
              'venv.lib.python3.6.site-packages.numpy.random', 'venv.lib.python3.6.site-packages.numpy.random.tests',
              'venv.lib.python3.6.site-packages.numpy.testing', 'venv.lib.python3.6.site-packages.numpy.testing.tests',
              'venv.lib.python3.6.site-packages.numpy.testing._private',
              'venv.lib.python3.6.site-packages.numpy.distutils',
              'venv.lib.python3.6.site-packages.numpy.distutils.tests',
              'venv.lib.python3.6.site-packages.numpy.distutils.command',
              'venv.lib.python3.6.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.6.site-packages.numpy.matrixlib',
              'venv.lib.python3.6.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.6.site-packages.numpy.polynomial',
              'venv.lib.python3.6.site-packages.numpy.polynomial.tests', 'venv.lib.python3.6.site-packages.sanic',
              'venv.lib.python3.6.site-packages.scipy', 'venv.lib.python3.6.site-packages.scipy.io',
              'venv.lib.python3.6.site-packages.scipy.io.arff', 'venv.lib.python3.6.site-packages.scipy.io.arff.tests',
              'venv.lib.python3.6.site-packages.scipy.io.tests', 'venv.lib.python3.6.site-packages.scipy.io.matlab',
              'venv.lib.python3.6.site-packages.scipy.io.matlab.tests',
              'venv.lib.python3.6.site-packages.scipy.io.harwell_boeing',
              'venv.lib.python3.6.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib.python3.6.site-packages.scipy.odr', 'venv.lib.python3.6.site-packages.scipy.odr.tests',
              'venv.lib.python3.6.site-packages.scipy._lib', 'venv.lib.python3.6.site-packages.scipy._lib.tests',
              'venv.lib.python3.6.site-packages.scipy.misc', 'venv.lib.python3.6.site-packages.scipy.misc.tests',
              'venv.lib.python3.6.site-packages.scipy.stats', 'venv.lib.python3.6.site-packages.scipy.stats.tests',
              'venv.lib.python3.6.site-packages.scipy.linalg', 'venv.lib.python3.6.site-packages.scipy.linalg.tests',
              'venv.lib.python3.6.site-packages.scipy.signal', 'venv.lib.python3.6.site-packages.scipy.signal.tests',
              'venv.lib.python3.6.site-packages.scipy.signal.windows', 'venv.lib.python3.6.site-packages.scipy.sparse',
              'venv.lib.python3.6.site-packages.scipy.sparse.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.csgraph',
              'venv.lib.python3.6.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib.python3.6.site-packages.scipy.cluster', 'venv.lib.python3.6.site-packages.scipy.cluster.tests',
              'venv.lib.python3.6.site-packages.scipy.fftpack', 'venv.lib.python3.6.site-packages.scipy.fftpack.tests',
              'venv.lib.python3.6.site-packages.scipy.ndimage', 'venv.lib.python3.6.site-packages.scipy.ndimage.tests',
              'venv.lib.python3.6.site-packages.scipy.spatial', 'venv.lib.python3.6.site-packages.scipy.spatial.tests',
              'venv.lib.python3.6.site-packages.scipy.special', 'venv.lib.python3.6.site-packages.scipy.special.tests',
              'venv.lib.python3.6.site-packages.scipy.special._precompute',
              'venv.lib.python3.6.site-packages.scipy.optimize', 'venv.lib.python3.6.site-packages.scipy.optimize._lsq',
              'venv.lib.python3.6.site-packages.scipy.optimize.tests',
              'venv.lib.python3.6.site-packages.scipy.optimize._trlib',
              'venv.lib.python3.6.site-packages.scipy.optimize._trustregion_constr',
              'venv.lib.python3.6.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.lib.python3.6.site-packages.scipy.constants',
              'venv.lib.python3.6.site-packages.scipy.constants.tests',
              'venv.lib.python3.6.site-packages.scipy.integrate',
              'venv.lib.python3.6.site-packages.scipy.integrate._ivp',
              'venv.lib.python3.6.site-packages.scipy.integrate.tests',
              'venv.lib.python3.6.site-packages.scipy.interpolate',
              'venv.lib.python3.6.site-packages.scipy.interpolate.tests',
              'venv.lib.python3.6.site-packages.scipy._build_utils', 'venv.lib.python3.6.site-packages.uvloop',
              'venv.lib.python3.6.site-packages.uvloop.includes', 'venv.lib.python3.6.site-packages.MySQLdb',
              'venv.lib.python3.6.site-packages.MySQLdb.constants', 'venv.lib.python3.6.site-packages.asyncio',
              'venv.lib.python3.6.site-packages.certifi', 'venv.lib.python3.6.site-packages.chardet',
              'venv.lib.python3.6.site-packages.chardet.cli', 'venv.lib.python3.6.site-packages.urllib3',
              'venv.lib.python3.6.site-packages.urllib3.util', 'venv.lib.python3.6.site-packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.aiofiles', 'venv.lib.python3.6.site-packages.aiofiles.threadpool',
              'venv.lib.python3.6.site-packages.pybase64', 'venv.lib.python3.6.site-packages.pybase64.tests',
              'venv.lib.python3.6.site-packages.pybase64.distutils', 'venv.lib.python3.6.site-packages.requests',
              'venv.lib.python3.6.site-packages.httptools', 'venv.lib.python3.6.site-packages.httptools.parser',
              'venv.lib.python3.6.site-packages.imagehash', 'venv.lib.python3.6.site-packages.imagehash.tests',
              'venv.lib.python3.6.site-packages.websockets', 'venv.lib.python3.6.site-packages.websockets.py35',
              'venv.lib.python3.6.site-packages.websockets.py36',
              'venv.lib.python3.6.site-packages.websockets.extensions'],
    url='',
    license='',
    author='amin',
    author_email='',
    description=''
)
